### ISSUE TITLE
Material transition ?

### ISSUE THREAD

**Issue by yanzacheus** [Garbee/Dropdown-Component#1]
Hello and thanks for the component.
Just to be sure that you did'nt provide any mdl transition animation when menu items collapse (I mean perhaps I did'nt build the files - or use the component - as necessary)
Because when I implemented that, it worked but without any transition animation that can be seen.
Thanks.

**Comment by Garbee** [comment]
Implementing an animation with this is slightly complex due to the variable height. I opted just to do a quick & dirty dropdown and be done with it. Beyond addressing some accessibility concerns as I have time this isn't a project I'm actively maintaining with new features. This was more of a simple example for others to use as a reference for building anyways.
